#
# Uncomment to clean all conversations for demo purposes
#

# Message.delete_all
# Conversation.delete_all
# UserConversation.delete_all

# 
#Uncomment to seed all interests
#

# Interest.delete_all

# hobbies = "3D printing,
# Acrobatics,
# Acting,
# Action figure,
# Air sports,
# Aircraft spotting,
# Airsoft,
# Amateur astronomy,
# Amateur radio,
# American football,
# Animal fancy,
# Animation,
# Antiquing,
# Antiquities,
# Aquascaping,
# Archery,
# Art collecting,
# Association football,
# Astrology,
# Astronomy,
# Australian rules football,
# Auto audiophilia,
# Auto racing,
# Badminton,
# Baking,
# Base jumping,
# Baseball,
# Basketball,
# Baton twirling,
# Beach volleyball,
# Beatboxing,
# Beekeeping,
# Billiards,
# Bird watching,
# Blacksmithing,
# BMX,
# Board games,
# Board sports,
# Bodybuilding,
# Book collecting,
# Book restoration,
# Bowling,
# Boxing,
# Brazilian jiu-jitsu,
# Breakdancing,
# Bridge,
# Bus spotting
# Cabaret,
# Calligraphy,
# Camping,
# Candle making,
# Canoeing,
# Canyoning,
# Card collecting,
# Cheerleading,
# Chess,
# Climbing,
# Coffee roasting,
# Coin collecting,
# Color guard,
# Coloring,
# Comic book collecting,
# Competitive eating,
# Computer programming,
# Cooking,
# Cosplaying,
# Couponing,
# Creative writing,
# Cricket,
# Crocheting,
# Cross-stitch,
# Crossword puzzles,
# Cryptography,
# Curling,
# Cycling,
# Dance,
# Dancing,
# Darts,
# Debate,
# Deltiology (postcard collecting),
# Die-cast toy,
# Digital arts,
# Disc golf,
# Do it yourself,
# Dog sport,
# Dowsing,
# Drama,
# Drawing,
# Driving,
# Electronics,
# Element collecting,
# Embroidery,
# Equestrianism,
# ESports,
# Exhibition drill,
# Fantasy sports,
# Fashion,
# Fencing,
# Field hockey,
# Figure skating,
# Fishing,
# Fishkeeping,
# Flag football,
# Flower arranging,
# Flower collecting and pressing,
# Flying disc,
# Flying,
# Footbag,
# Foraging,
# Foreign language learning,
# Fossil hunting,
# Freestyle football,
# Gardening,
# Genealogy,
# Geocaching,
# Ghost hunting,
# Glassblowing,
# Go,
# Golfing,
# Gongoozling,
# Graffiti,
# Graphic Design,
# Gunsmithing,
# Gymnastics,
# Handball,
# Herp keeping,
# Herping,
# High-power rocketry,
# Hiking,
# Backpacking,
# Homebrewing,
# Hooping,
# Horseback riding,
# Hunting,
# Hydroponics,
# Ice hockey,
# Ice skating,
# Indoors,
# Inline skating,
# Insect collecting,
# Jewelry making,
# Jigsaw puzzles,
# Jogging,
# Judo,
# Juggling,
# Jukskei,
# Kabaddi,
# Kart racing,
# Kayaking,
# Kite flying,
# Kitesurfing,
# Knife making,
# Knife throwing,
# Knitting,
# Kombucha brewing,
# Lace making,
# Lacrosse,
# Lapidary,
# LARPing,
# Laser tag,
# Learning,
# Leather crafting,
# Lego building,
# Letterboxing,
# Listening to music,
# Longboarding,
# Machining,
# Macrame,
# Magic,
# Magnet fishing,
# Mahjong,
# Marbles,
# Marching band,
# Martial arts,
# Metal detecting,
# Metalworking,
# Meteorology,
# Microscopy,
# Mineral collecting,
# Model aircraft,
# Model building,
# Model engineering,
# Motor sports,
# Mountain biking,
# Mountaineering,
# Movie and movie memorabilia collecting,
# Mushroom hunting/mycology,
# Needlepoint,
# Netball,
# Nordic skating,
# Observation hobbies,
# Orienteering,
# Origami,
# Outdoors,
# Paintball,
# Painting,
# Parkour,
# Pet,
# Philately,
# Phillumeny,
# Photography,
# Playing musical instruments,
# Poi,
# Poker,
# Polo,
# Pottery,
# Powerlifting,
# Puzzles,
# Quilling,
# Quilting,
# Racquetball,
# Radio-controlled car racing,
# Rafting,
# Rail transport modelling,
# Rappelling,
# Reading,
# Record collecting,
# Road biking,
# Rock balancing,
# Rock climbing,
# Roller derby,
# Roller skating,
# Rugby league football,
# Rugby,
# Running,
# Sailing,
# Sand art,
# Satellite watching,
# Scouting,
# Scrapbooking,
# Scuba diving,
# Sculling or rowing,
# Sculpting,
# Sea glass collecting,
# Seashell collecting,
# Sewing,
# Shoes,
# Shooting sport,
# Shooting,
# Shopping,
# Shortwave listening,
# Singing,
# Skateboarding,
# Sketching,
# Skiing,
# Skimboarding,
# Skydiving,
# Slacklining,
# Slot car racing,
# Snowboarding,
# Soapmaking,
# Speed skating,
# Speedcubing,
# Sport stacking,
# Squash,
# Stamp collecting,
# Stand-up comedy,
# Stone collecting,
# Stone skipping,
# Sun bathing,
# Surfing,
# Swimming,
# Table football,
# Table tennis,
# Taekwondo,
# Tai chi,
# Taxidermy,
# Tennis polo,
# Tennis,
# Tether car,
# Topiary,
# Tour skating,
# Trainspotting,
# Traveling,
# Triathlon,
# Ultimate frisbee,
# Urban exploration,
# Vacation,
# Vehicle restoration,
# Video game collecting,
# Video game developing,
# Video gaming,
# Videophilia,
# Vintage cars,
# Volleyball,
# Walking,
# Watching movies,
# Watching television,
# Water polo,
# Water sports,
# Weightlifting,
# Whale watching
# Whittling,
# Wood carving,
# Woodworking,
# Worldbuilding,
# Wrestlingter source needed,
# Writing,
# Yo-yoing,
# Yoga,"

# hobbies.split(",").each { |hobbie| Interest.create(name: hobbie.downcase.strip)}